from enum import Enum


class AspectName(Enum):
    CONJ = 'CONJ'
    SEMISEXTILE = 'SEMISEXTILE'
    SEXTILE = 'SEXTILE'
    SEMISQUARE = 'SEMISQUARE'
    SQUARE = 'SQUARE'
    TRINE = 'TRINE'
    QUINCUNX = 'QUINCUNX'
    OPPOSITION = 'OPPOSITION'
    BIQUINTILE = 'BIQUINTILE'
    QUINTILE = 'QUINTILE'
    SESQUISQUARE = 'SESQUISQUARE'
